version: '3.8'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  postgresql:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: drawcen
      POSTGRES_USER: yagumyagum
      POSTGRES_PASSWORD: yagumyagum
    volumes:
      - pg-data:/var/lib/postgresql/data

  spring:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - redis
      - postgresql

volumes:
  mongo-data:
  redis-data:
  pg-data:
